### Test de l'action "Gris"
POST http://127.0.0.1:8000/process/?action=gray
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="mon_image.jpg"
Content-Type: image/jpeg

< ./test.jpg
--boundary--

### Test de l'action "Rotation"
POST http://127.0.0.1:8000/process/?action=rotate90
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="mon_image.jpg"
Content-Type: image/jpeg

< ./test.jpg
--boundary--

### Vérifier la liste des fichiers (GET)
GET http://127.0.0.1:8000/files


### Vérifier la santé du serveur (GET)
GET http://127.0.0.1:8000/health