### "Grey" test
POST http://127.0.0.1:8000/process/?action=gray
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="mon_image.jpg"
Content-Type: image/jpeg

< ./test.jpg
--boundary--

### "Rotation" test
POST http://127.0.0.1:8000/process/?action=rotate90
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="mon_image.jpg"
Content-Type: image/jpeg

< ./test.jpg
--boundary--

### Check files list(GET)
GET http://127.0.0.1:8000/files


### Check server health (GET)
GET http://127.0.0.1:8000/health