name: Continuous Integration & Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    # 1. Récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Installer les dépendances C++ et OpenCV sur le runner GitHub
    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libopencv-dev python3-dev

    # 3. Configurer l'environnement Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    # 4. Installer les libs Python
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybind11 setuptools wheel
        pip install -r backend/requirements.txt

    # 5. Tester la compilation du module C++ en natif
    - name: Compile C++ Binding
      run: |
        cd backend
        python3 setup.py build_ext --inplace

    # 6. Build de l'image Docker (Vérification finale)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  # <-- CORRECTION : Docker le cherche maintenant à la racine !
        push: false
        tags: photolab-backend:latest